version: '3'

services:
  nginx:
    build: requirements/nginx
    restart: always
    # depends_on:
    #   - wordpress
    ports:
      - "443:443"
      - "80"
    networks:
      - docker-network

  mariadb:
    build: requirements/mariadb
    restart: always
    networks:
      - docker-network
    volumes:
      - ~/Desktop/inception/mariadb:/var/lib/mysql
    #TODO: あとで消す。 デバッグ用
    # MySQL のポート 3306 を開けてホストから繋げられるか確かめてみる
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USER}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

  # wordpress:
  #   build: requirements/wordpress
  #   restart: always
  #   networks:
  #     - docker-network
  #   depends_on:
  #     - mariadb
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  #   container_name: wordpress

networks:
  docker-network: