version: '3'

services:
  nginx:
    build: requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - docker-network
    volumes:
      - wordpress_data:/var/www/html/wordpress

  mariadb:
    build: requirements/mariadb
    restart: always
    networks:
      - docker-network
    volumes:
      - mariadb_data:/var/lib/mysql
    #TODO: あとでexposeに書き換える。 デバッグ用
    # MySQL のポート 3306 を開けてホストから繋げられるか確かめてみる
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USER: ${WP_DATABASE_USER}
      WP_DATABASE_PASSWORD: ${WP_DATABASE_PASSWORD}

  wordpress:
    build: requirements/wordpress
    restart: always
    networks:
      - docker-network
    depends_on:
      - mariadb
    ports:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    environment:
      DB_HOST: mariadb
      DB_USER: ${WP_DATABASE_USER}
      DB_PASSWORD: ${WP_DATABASE_PASSWORD}
      DB_NAME: ${WP_DATABASE_NAME}

networks:
  docker-network:

volumes:
  wordpress_data: {}
  mariadb_data: {}
