version: '3'

services:
  nginx:
    build: requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    networks:
      - docker-network

  mariadb:
    build: requirements/mariadb
    restart: always
    networks:
      - docker-network
    volumes:
      - ~/Desktop/inception/mariadb:/var/lib/mysql
    #TODO: あとでexposeに書き換える。 デバッグ用
    # MySQL のポート 3306 を開けてホストから繋げられるか確かめてみる
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USER}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

  wordpress:
    build: requirements/wordpress
    restart: always
    networks:
      - docker-network
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mariadb
      DB_USER: ${WP_DATABASE_USER}
      DB_PASSWORD: ${WP_DATABASE_PWD}
      DB_NAME: ${WP_DATABASE_NAME}

networks:
  docker-network:
